export const EMAIL_MISSING = 'Your email is missing';
export const PASSWORD_MISSING = 'Your password is missing';
export const CONFIRMATION_PASSWORD_MISSING = 'Your confirmation password is missing';
export const INVALID_EMAIL = 'This is an invalid email';
export const EMAIL_ALREADY_IN_USE = 'This email is already in use';
export const EMAIL_DOES_NOT_EXIST = 'This email does not exist';
export const INCORRECT_PASSWORD = 'This is the wrong password';
export const INVALID_PASSWORD_LENGTH = 'The password must be 6 to 30 characters in length';
export const PASSWORD_MISMATCH = 'Your passwords do not match';
