export const FETCH_USER = 'FETCH_USER';
export const SIGN_UP_USER = 'SIGN_UP_USER';
export const SIGN_IN_USER = 'SIGN_IN_USER';
export const SIGN_OUT_USER = 'SIGN_OUT_USER';

export const FETCH_USER_REVIEWS = 'FETCH_USER_REVIEWS';
export const NEW_USER_REVIEW = 'NEW_USER_REVIEW';
export const EDIT_USER_REVIEW = 'EDIT_USER_REVIEW';
export const DELETE_USER_REVIEW = 'DELETE_USER_REVIEW';


export const FETCH_PROFILE = 'FETCH_PROFILE';
export const NEW_PROFILE = 'NEW_PROFILE';

export const GET_ITEM_REVIEWS = 'GET_ITEM_REVIEWS';
export const DELETE_ITEM_REVIEW = 'DELETE_ITEM_REVIEW';
export const NEW_ITEM_REVIEW = 'NEW_ITEM_REVIEW';
export const EDIT_ITEM_REVIEW = 'EDIT_ITEM_REVIEW';

export const FILTER_ITEMS = 'FILTER_ITEMS';
export const GET_ITEM = 'GET_ITEM';
export const GET_MY_ITEMS = 'GET_MY_ITEMS';

export const GET_MY_TRANSACTIONS = 'GET_MY_TRANSACTIONS';
export const NEW_TRANSACTION = 'NEW_TRANSACTION';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';

export const NEW_ITEM = 'NEW_ITEM';